#!/usr/bin/env bash
# Change localhost address

# Configure localhost to resolve to 127.0.0.2
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts

# Configure facebook.com to resolve to 8.8.8.8
sudo sed -i 's/157.240.11.35/8.8.8.8/g' /etc/hosts
